version: "3"
services:
  mongodb:
    image: bitnami/mongodb:latest
    restart: unless-stopped
    networks: 
      - t20
    # environment: 
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    logging:
      driver: none
  server:
    depends_on: 
    - mongodb
    image: tuanminh009/iot-be:v1
    ports:
      - '3001:3001'
    environment:
      DB_URL: mongodb://mongodb:27017
    networks:
      - t20
  client: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
    networks:
      - t20
networks:
  t20:
    driver: bridge